name: Rust

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-musl, x86_64-apple-darwin]
    steps:
      - uses: actions/checkout@v4
      - name: Update runner
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install gtk2.0-dev gtk-3-dev
      - name: Install Rust
        run: rustup toolchain install stable --profile minimal
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build --verbose
      #- uses: clechasseur/rs-clippy-check@v3
      #  with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    args: --no-default-features --features gui-vizia
      - uses: clechasseur/rs-clippy-check@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features gui-egui
      - name: Run tests
        run: cargo test --workspace --no-default-features --features components --verbose
      - name: Build RISC-V
        run: | 
          cd riscv
          cargo build --example riscv --verbose
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: rustfmt
        run: cargo fmt --all -- --check
